//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXREPORTHRGIS.PredefinedReports {
    
    public partial class CourseMap : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "DXREPORTHRGIS.PredefinedReports.CourseMap.vsrepx");

            // Controls
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.crossTab1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCrossTab>("crossTab1");
            this.crossTabCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell1");
            this.crossTabCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell2");
            this.crossTabCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell3");
            this.crossTabCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell4");
            this.crossTabCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell5");
            this.crossTabCell6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell6");
            this.crossTabCell7 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell7");
            this.crossTabCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell8");
            this.crossTabCell9 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell9");
            this.crossTabCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell10");
            this.crossTabCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell12");
            this.crossTabCell13 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell13");
            this.crossTabCell15 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell15");
            this.crossTabCell17 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell17");
            this.crossTabCell18 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell18");
            this.crossTabCell19 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell19");
            this.crossTabCell20 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell20");
            this.crossTabCell21 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell21");
            this.crossTabCell22 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell22");
            this.crossTabCell23 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell23");
            this.crossTabCell24 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell24");
            this.crossTabCell25 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell25");
            this.crossTabCell26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell26");
            this.crossTabCell27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell27");
            this.crossTabCell28 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell28");
            this.crossTabCell29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell29");
            this.crossTabCell30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell30");
            this.crossTabCell31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell31");
            this.crossTabCell32 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell32");
            this.crossTabCell33 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell33");
            this.crossTabCell34 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell34");
            this.crossTabCell35 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell35");
            this.crossTabCell36 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell36");
            this.crossTabCell37 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell37");
            this.crossTabCell38 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell38");
            this.crossTabCell39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell39");
            this.crossTabCell40 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell40");
            this.crossTabCell41 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell41");
            this.crossTabCell42 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell42");
            this.crossTabCell43 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell43");
            this.crossTabCell44 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell44");
            this.crossTabCell45 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell45");
            this.crossTabCell46 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell46");
            this.crossTabCell47 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell47");
            this.crossTabCell48 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell48");
            this.crossTabCell49 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell49");
            this.crossTabCell50 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell50");
            this.crossTabCell51 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell51");
            this.crossTabCell52 = reportInitializer.GetControl<DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell>("crossTabCell52");
            this.pageInfo2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo2");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");

            // Parameters
            this.DIV = reportInitializer.GetParameter("DIV");
            this.DEPT = reportInitializer.GetParameter("DEPT");
            this.STATUS = reportInitializer.GetParameter("STATUS");

            // Data Sources
            this.sqlDataSource2 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource2");

            // Calculated Fields
            this.calculatedField1 = reportInitializer.GetCalculatedField("calculatedField1");

            // Styles
            this.TitleStyle = reportInitializer.GetStyle("TitleStyle");
            this.crossTabGeneralStyle = reportInitializer.GetStyle("crossTabGeneralStyle");
            this.crossTabHeaderStyle = reportInitializer.GetStyle("crossTabHeaderStyle");
            this.crossTabDataStyle = reportInitializer.GetStyle("crossTabDataStyle");
            this.crossTabTotalStyle = reportInitializer.GetStyle("crossTabTotalStyle");
        }
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRCrossTab crossTab1;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell1;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell2;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell3;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell4;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell5;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell6;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell7;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell8;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell9;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell10;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell12;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell13;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell15;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell17;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell18;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell19;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell20;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell21;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell22;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell23;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell24;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell25;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell26;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell27;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell28;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell29;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell30;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell31;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell32;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell33;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell34;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell35;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell36;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell37;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell38;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell39;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell40;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell41;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell42;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell43;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell44;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell45;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell46;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell47;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell48;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell49;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell50;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell51;
        private DevExpress.XtraReports.UI.CrossTab.XRCrossTabCell crossTabCell52;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource2;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo2;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
        private DevExpress.XtraReports.UI.XRControlStyle TitleStyle;
        private DevExpress.XtraReports.UI.XRControlStyle crossTabGeneralStyle;
        private DevExpress.XtraReports.UI.XRControlStyle crossTabHeaderStyle;
        private DevExpress.XtraReports.UI.XRControlStyle crossTabDataStyle;
        private DevExpress.XtraReports.UI.XRControlStyle crossTabTotalStyle;
        private DevExpress.XtraReports.UI.CalculatedField calculatedField1;
        private DevExpress.XtraReports.Parameters.Parameter DIV;
        private DevExpress.XtraReports.Parameters.Parameter DEPT;
        private DevExpress.XtraReports.Parameters.Parameter STATUS;
    }
}
